@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
package ke.co.nsewatcher

import android.app.Application
import android.content.Context
import android.content.SharedPreferences
import android.graphics.BitmapFactory
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import ke.co.nsewatcher.data.DemoMarketRepository
import ke.co.nsewatcher.data.MarketRepository
import ke.co.nsewatcher.domain.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

private val Green=Color(0xFF00A859)
private val LightGreen=Color(0xFFE8F8EF)
private val Red=Color(0xFFE53935)
private val TextDark=Color(0xFF102018)
private val Muted=Color(0xFF68766F)
private val BorderGreen=Color(0xFFE0EAE4)
private val AppColors=lightColorScheme(primary=Green,onPrimary=Color.White,secondary=Green,tertiary=Green,background=Color.White,surface=Color.White,surfaceVariant=Color(0xFFF4F7F5),onBackground=TextDark,onSurface=TextDark,onSurfaceVariant=Muted,error=Red)
private val DarkAppColors=darkColorScheme(primary=Color(0xFF35C979),onPrimary=Color(0xFF00391C),secondary=Color(0xFF35C979),background=Color(0xFF0E1511),surface=Color(0xFF16201A),surfaceVariant=Color(0xFF223027),onBackground=Color.White,onSurface=Color.White,onSurfaceVariant=Color(0xFFB8C6BD),error=Color(0xFFFF6B64))

data class AppState(val snapshot:MarketSnapshot?=null,val news:List<NewsItem>=emptyList(),val loading:Boolean=true,val error:String?=null)
data class Holding(val symbol:String,val shares:Int,val averagePrice:Double)

class MainActivity:ComponentActivity(){
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{NSEWatcherApp(MarketViewModel(application),getSharedPreferences("nse_watcher_user",Context.MODE_PRIVATE))}}
}

class MarketViewModel(application:Application,private val repository:MarketRepository=DemoMarketRepository(application)):ViewModel(){
    private val _state=MutableStateFlow(AppState());val state:StateFlow<AppState> = _state
    init{refresh()}
    fun refresh()=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);repository.snapshot(true).onSuccess{s->repository.news().onSuccess{n->_state.value=AppState(s,n,false)}}.onFailure{_state.value=_state.value.copy(loading=false,error=it.message?:"Unable to load market data")}}
    fun add(symbol:String)=viewModelScope.launch{repository.addSymbol(symbol);refresh()}
    fun remove(symbol:String)=viewModelScope.launch{repository.removeSymbol(symbol);refresh()}
}

@Composable fun NSEWatcherApp(vm:MarketViewModel,prefs:SharedPreferences){
    val state by vm.state.collectAsStateWithLifecycle()
    var tab by rememberSaveable{mutableIntStateOf(0)}
    var selected by remember{mutableStateOf<Quote?>(null)}
    var settings by rememberSaveable{mutableStateOf(false)}
    var account by rememberSaveable{mutableStateOf(false)}
    var appearance by rememberSaveable{mutableStateOf(false)}
    var infoDialog by rememberSaveable{mutableStateOf<String?>(null)}
    var searchOpen by rememberSaveable{mutableStateOf(false)}
    var darkMode by rememberSaveable{mutableStateOf(prefs.getBoolean("dark_mode",false))}
    var username by rememberSaveable{mutableStateOf(prefs.getString("username","jimmymwangi")?:"jimmymwangi")}
    var email by rememberSaveable{mutableStateOf(prefs.getString("email","jimmy.mwangi@email.com")?:"jimmy.mwangi@email.com")}
    var password by rememberSaveable{mutableStateOf(prefs.getString("password","password123")?:"password123")}
    var description by rememberSaveable{mutableStateOf(prefs.getString("description","Building wealth, one stock at a time.")?:"Building wealth, one stock at a time.")}
    var avatarUri by rememberSaveable{mutableStateOf(prefs.getString("avatar_uri",null))}
    var holdings by remember{mutableStateOf(listOf(Holding("SCOM.KE",500,21.50),Holding("KCB.KE",200,38.00)))}
    var alerts by remember{mutableStateOf(listOf("SCOM.KE above KSh 30.00","KCB.KE daily gain above 5%","EABL.KE volume above average"))}
    fun savePrefs(){prefs.edit().putBoolean("dark_mode",darkMode).putString("username",username).putString("email",email).putString("password",password).putString("description",description).putString("avatar_uri",avatarUri).apply()}
    val internalBackEnabled=settings||account||appearance||selected!=null||tab!=0||searchOpen
    BackHandler(enabled=internalBackEnabled){when{searchOpen->{searchOpen=false};account->{account=false};appearance->{appearance=false};settings->{settings=false};selected!=null->{selected=null};tab!=0->{tab=0}}}
    MaterialTheme(colorScheme=if(darkMode)DarkAppColors else AppColors){Surface(Modifier.fillMaxSize(),color=MaterialTheme.colorScheme.background){when{account->AccountSettingsScreen(username,email,password,description,avatarUri,{account=false},{username=it},{email=it},{password=it},{description=it},{avatarUri=it;savePrefs()});appearance->AppearanceScreen(darkMode,{appearance=false}){darkMode=it;savePrefs()};settings->SettingsScreen(username,description,avatarUri,{settings=false},{account=true},{appearance=true},{infoDialog="Notifications will connect to alert preferences and push delivery in the live phase."},{infoDialog="Security controls will be enabled when account authentication is connected."},{infoDialog="Help and support will be connected before production release."});selected!=null->DetailScreen(selected!!){selected=null};else->MainShell(state,vm,tab,{tab=it},{selected=it},{settings=true},{searchOpen=true},holdings,{holdings=it},alerts,{alerts=it},{tab=1})};if(searchOpen)SearchDialog(state.snapshot?.quotes.orEmpty(),{searchOpen=false;selected=it},{searchOpen=false})};infoDialog?.let{msg->AlertDialog(onDismissRequest={infoDialog=null},confirmButton={TextButton(onClick={infoDialog=null}){Text("OK")}},title={Text("NSE Watcher")},text={Text(msg)})}}}
}

@Composable private fun MainShell(state:AppState,vm:MarketViewModel,tab:Int,setTab:(Int)->Unit,open:(Quote)->Unit,openSettings:()->Unit,openSearch:()->Unit,holdings:List<Holding>,setHoldings:(List<Holding>)->Unit,alerts:List<String>,setAlerts:(List<String>)->Unit,viewAllWatchlist:()->Unit){
    Scaffold(topBar={TopBar(openSettings,openSearch)},bottomBar={NavigationBar(containerColor=MaterialTheme.colorScheme.surface){val nav=listOf("Home" to Icons.Default.Home,"Watchlist" to Icons.Default.Star,"Portfolio" to Icons.Default.AccountBalanceWallet,"Alerts" to Icons.Default.Notifications,"News" to Icons.Default.Article);nav.forEachIndexed{i,item->NavigationBarItem(selected=tab==i,onClick={setTab(i)},icon={Icon(item.second,item.first,modifier=Modifier.size(24.dp))},label={Text(item.first)},colors=NavigationBarItemDefaults.colors(selectedIconColor=Green,selectedTextColor=Green,indicatorColor=LightGreen,unselectedIconColor=Muted,unselectedTextColor=Muted))}}}){padding->Box(Modifier.fillMaxSize().padding(padding)){when{state.loading->CircularProgressIndicator(Modifier.align(Alignment.Center),color=Green);state.error!=null&&state.snapshot==null->ErrorState(state.error!!,vm::refresh);tab==0->Dashboard(state,open,viewAllWatchlist);tab==1->Watchlist(state.snapshot?.quotes.orEmpty(),vm::add,vm::remove,open);tab==2->PortfolioScreen(holdings,setHoldings);tab==3->AlertsScreen(alerts,setAlerts);else->NewsScreen(state.news)}}}}

@Composable private fun TopBar(openSettings:()->Unit,openSearch:()->Unit){TopAppBar(colors=TopAppBarDefaults.topAppBarColors(containerColor=MaterialTheme.colorScheme.surface),title={Row(verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(40.dp),shape=RoundedCornerShape(11.dp),color=LightGreen){Icon(Icons.Default.ShowChart,null,tint=Green,modifier=Modifier.size(27.dp).padding(1.dp))};Spacer(Modifier.width(9.dp));Column{Text("NSE Watcher",fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.titleMedium);Text("Track • Analyze • Grow",style=MaterialTheme.typography.labelSmall,color=Muted)}}},actions={IconButton(onClick=openSearch){Icon(Icons.Default.Search,"Search",tint=Green,modifier=Modifier.size(27.dp))};IconButton(onClick=openSettings){Icon(Icons.Default.Settings,"Settings",tint=Green,modifier=Modifier.size(29.dp))}})}

@Composable private fun Dashboard(state:AppState,open:(Quote)->Unit,viewAll:()->Unit){
    val quotes=state.snapshot?.quotes.orEmpty();val gainers=quotes.sortedByDescending{it.dailyChange};val losers=quotes.sortedBy{it.dailyChange}
    LazyColumn(contentPadding=PaddingValues(start=16.dp,end=16.dp,top=8.dp,bottom=18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
        item{MarketHero(state.snapshot?.updatedAt?.toString()?.take(16)?:"—")}
        item{MarketSummary(quotes)}
        item{SectionTitle("Market Indices","NSE benchmark snapshot")};item{IndicesRow()}
        item{SectionTitleWithAction("🔥 Market Movers","Top gainers and losers","View All",{})};item{MarketMovers(gainers.take(4),losers.take(4),open)}
        item{SectionTitleWithAction("⭐ Your Watchlist","Your tracked stocks","View All",viewAll)};item{LazyRow(contentPadding=PaddingValues(horizontal=1.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){items(quotes.take(6),key={it.symbol}){q->HorizontalStockCard(q){open(q)}}}}
        item{SectionTitle("🧠 NSE Watcher Intelligence","Explainable demo analysis")};item{IntelligenceSummary(quotes)}
        item{SectionTitleWithAction("📰 Latest News","From your tracked stocks","View All",{})};items(state.news.take(3),key={it.id}){NewsCard(it)}
        item{DemoBanner()}
    }
}

@Composable private fun MarketHero(updated:String){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Row(Modifier.fillMaxWidth().padding(horizontal=15.dp,vertical=13.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(9.dp).clip(CircleShape).background(Green));Spacer(Modifier.width(7.dp));Text("MARKET SESSION",fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelLarge)};Spacer(Modifier.height(3.dp));Text("DEMO MARKET",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold,color=Green);Text("Sample prices • not live data",style=MaterialTheme.typography.bodySmall,color=Muted);Text("Updated $updated",style=MaterialTheme.typography.labelSmall,color=Muted)};Column(horizontalAlignment=Alignment.End){Text("NSE",fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.titleLarge);Text("Nairobi Securities\nExchange",style=MaterialTheme.typography.labelSmall,color=Muted,textAlign=TextAlign.End)}}}}

@Composable private fun MarketSummary(quotes:List<Quote>){val gain=quotes.count{it.dailyChange>0};val loss=quotes.count{it.dailyChange<0};val flat=quotes.size-gain-loss;Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(13.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(vertical=9.dp),horizontalArrangement=Arrangement.SpaceEvenly){SummaryStat("Stocks",quotes.size.toString(),Green,Modifier.weight(1f));SummaryDivider();SummaryStat("Gainers",gain.toString(),Green,Modifier.weight(1f));SummaryDivider();SummaryStat("Losers",loss.toString(),Red,Modifier.weight(1f));SummaryDivider();SummaryStat("Unchanged",flat.toString(),TextDark,Modifier.weight(1f))}}}
@Composable private fun SummaryDivider(){Box(Modifier.width(1.dp).height(34.dp).background(BorderGreen))}
@Composable private fun SummaryStat(label:String,value:String,tint:Color,modifier:Modifier){Column(modifier,horizontalAlignment=Alignment.CenterHorizontally){Text(value,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold,color=tint);Text(label,style=MaterialTheme.typography.labelSmall,color=Muted)}}
@Composable private fun SectionTitle(title:String,subtitle:String){Column{Text(title,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.ExtraBold);Text(subtitle,color=Muted,style=MaterialTheme.typography.labelSmall)}}
@Composable private fun SectionTitleWithAction(title:String,subtitle:String,action:String,onAction:()->Unit){Row(Modifier.fillMaxWidth().padding(top=2.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.ExtraBold);Text(subtitle,color=Muted,style=MaterialTheme.typography.labelSmall)};TextButton(onClick=onAction,contentPadding=PaddingValues(horizontal=2.dp,vertical=0.dp)){Text(action,color=Green,fontWeight=FontWeight.Bold);Icon(Icons.Default.ChevronRight,null,tint=Green,modifier=Modifier.size(18.dp))}}}

@Composable private fun IndicesRow(){LazyRow(horizontalArrangement=Arrangement.spacedBy(9.dp)){items(DemoIntelligenceData.indices){index->Card(Modifier.width(150.dp),shape=RoundedCornerShape(14.dp),border=BorderStroke(1.dp,BorderGreen)){Column(Modifier.padding(11.dp)){Text(index.name,fontWeight=FontWeight.ExtraBold);Text("%.2f".format(index.value),style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text("%+.2f%%".format(index.change),color=if(index.change>=0)Green else Red,fontWeight=FontWeight.Bold);Text(index.description,color=Muted,style=MaterialTheme.typography.labelSmall,maxLines=1)}}}}}

@Composable private fun MarketMovers(gainers:List<Quote>,losers:List<Quote>,open:(Quote)->Unit){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(vertical=12.dp)){MoverColumn("Top Gainers",gainers,true,Modifier.weight(1f),open);Box(Modifier.width(1.dp).height(170.dp).background(BorderGreen));MoverColumn("Top Losers",losers,false,Modifier.weight(1f),open)}}}
@Composable private fun MoverColumn(title:String,quotes:List<Quote>,positive:Boolean,modifier:Modifier,open:(Quote)->Unit){Column(modifier.padding(horizontal=13.dp)){Row(verticalAlignment=Alignment.CenterVertically){Icon(if(positive)Icons.Default.ArrowUpward else Icons.Default.ArrowDownward,null,tint=if(positive)Green else Red,modifier=Modifier.size(22.dp));Spacer(Modifier.width(5.dp));Text(title,style=MaterialTheme.typography.titleSmall,fontWeight=FontWeight.ExtraBold,color=if(positive)Green else Red)};Spacer(Modifier.height(8.dp));quotes.forEach{q->MoverRow(q,positive){open(q)}}}}
@Composable private fun MoverRow(q:Quote,positive:Boolean,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(onClick=onClick).padding(vertical=4.dp),verticalAlignment=Alignment.CenterVertically){StockLogo(q.symbol,30);Spacer(Modifier.width(7.dp));Text(q.symbol.removeSuffix(".KE"),fontWeight=FontWeight.Bold,style=MaterialTheme.typography.bodyMedium,modifier=Modifier.weight(1f));Text("%+.1f%%".format(q.dailyChange),fontWeight=FontWeight.ExtraBold,color=if(positive)Green else Red,style=MaterialTheme.typography.bodyMedium)}}
@Composable private fun StockLogo(symbol:String,size:Int){val short=symbol.removeSuffix(".KE");val bg=when(short){"SCOM"->Color(0xFF0B8F4D);"KCB"->Color(0xFF1B4D9B);"EQTY"->Color(0xFF137A45);"ABSA"->Color(0xFFC6283D);"COOP"->Color(0xFF1769AA);"EABL"->Color(0xFFB8A23A);"KPLC"->Color(0xFF285C8C);"BAT"->Color(0xFF243B75);else->Green};Surface(Modifier.size(size.dp),shape=RoundedCornerShape(size.dp/3),color=bg){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text(short.take(3),color=Color.White,fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.labelSmall)}}}

@Composable private fun HorizontalStockCard(q:Quote,open:()->Unit){val tint=if(q.dailyChange>=0)Green else Red;Card(Modifier.width(188.dp).clickable(onClick=open),shape=RoundedCornerShape(15.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(11.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){StockLogo(q.symbol,25);Spacer(Modifier.width(6.dp));Column(Modifier.weight(1f)){Text(q.symbol.removeSuffix(".KE"),fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.bodyMedium);Text(q.companyName.replace(" PLC", ""),color=Muted,style=MaterialTheme.typography.labelSmall,maxLines=1)}};Text("KSh %.2f".format(q.price),style=MaterialTheme.typography.labelSmall,fontWeight=FontWeight.Bold)};Spacer(Modifier.height(6.dp));Text("%+.2f%%".format(q.dailyChange),color=tint,fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.titleMedium);Sparkline(q.history,Modifier.fillMaxWidth().height(38.dp),tint)}}

@Composable private fun IntelligenceSummary(quotes:List<Quote>){val best=quotes.maxByOrNull{DemoIntelligenceData.score(it).total};val score=best?.let{DemoIntelligenceData.score(it)};Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Row(Modifier.fillMaxWidth().padding(13.dp),verticalAlignment=Alignment.CenterVertically){ScoreBadge(score?.total?:0,54);Spacer(Modifier.width(11.dp));Column(Modifier.weight(1f)){Text("Highest demo score",fontWeight=FontWeight.Bold);Text("${best?.symbol?.removeSuffix(".KE")?:"—"} • ${score?.label?:"—"}",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.ExtraBold);Text("Momentum, trend, volume and liquidity are combined transparently.",color=Muted,style=MaterialTheme.typography.bodySmall)}}}}

@Composable private fun NewsCard(item:NewsItem){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(15.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(9.dp),verticalAlignment=Alignment.CenterVertically){NewsThumbnail(item.category);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(item.headline,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.bodyMedium,maxLines=2);Spacer(Modifier.height(3.dp));Text("${item.source} • ${item.publishedAt}",color=Muted,style=MaterialTheme.typography.labelSmall,maxLines=1)};Icon(Icons.Default.ChevronRight,null,tint=Muted,modifier=Modifier.size(22.dp))}}}
@Composable private fun NewsThumbnail(category:String){val icon=when(category){"Company"->Icons.Default.Business;"Market"->Icons.Default.TrendingUp;else->Icons.Default.Article};Surface(Modifier.size(88.dp),shape=RoundedCornerShape(12.dp),color=LightGreen){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Icon(icon,null,tint=Green,modifier=Modifier.size(39.dp))}}}

@Composable private fun Sparkline(values:List<Double>,modifier:Modifier,tint:Color){Canvas(modifier){if(values.size>1){val min=values.minOrNull()?:0.0;val max=values.maxOrNull()?:1.0;val range=(max-min).takeIf{it>0}?:1.0;val path=Path();values.forEachIndexed{i,v->val x=size.width*i/values.lastIndex;val y=size.height-((v-min)/range).toFloat()*size.height;if(i==0)path.moveTo(x,y)else path.lineTo(x,y)};drawPath(path,tint,style=androidx.compose.ui.graphics.drawscope.Stroke(width=3.5f))}}}

@Composable private fun Watchlist(quotes:List<Quote>,add:(String)->Unit,remove:(String)->Unit,open:(Quote)->Unit){var search by rememberSaveable{mutableStateOf("")};var expanded by remember{mutableStateOf(false)};val catalog=listOf("SCOM.KE","EQTY.KE","KCB.KE","ABSA.KE","COOP.KE","EABL.KE","KPLC.KE");val filtered=quotes.filter{it.companyName.contains(search,true)||it.symbol.contains(search,true)};Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth().padding(16.dp),verticalAlignment=Alignment.CenterVertically){OutlinedTextField(search,{search=it},Modifier.weight(1f),singleLine=true,label={Text("Search stocks")},leadingIcon={Icon(Icons.Default.Search,null)});Spacer(Modifier.width(8.dp));Box{Button(onClick={expanded=true}){Icon(Icons.Default.Add,null);Text("Add")};DropdownMenu(expanded,{expanded=false}){catalog.forEach{sym->DropdownMenuItem(text={Text(sym)},onClick={add(sym);expanded=false})}}}};LazyColumn(contentPadding=PaddingValues(horizontal=16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(filtered,key={it.symbol}){q->StockCard(q){open(q)};TextButton(onClick={remove(q.symbol)}){Icon(Icons.Default.DeleteOutline,null);Text("Remove from watchlist")}}}}}

@Composable private fun StockCard(q:Quote,open:()->Unit){val tint=if(q.dailyChange>=0)Green else Red;Card(Modifier.fillMaxWidth().clickable(onClick=open),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(14.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(q.companyName,fontWeight=FontWeight.ExtraBold);Text(q.symbol,color=Muted,style=MaterialTheme.typography.bodySmall)};Column(horizontalAlignment=Alignment.End){Text("KSh %.2f".format(q.price),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Text("%+.1f%%".format(q.dailyChange),color=tint,fontWeight=FontWeight.Bold)}};Spacer(Modifier.height(8.dp));Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Stat("1W",q.weeklyChange,Modifier.weight(1f));Stat("1M",q.monthlyChange,Modifier.weight(1f));Column(Modifier.weight(1.2f)){Text("Volume",color=Muted,style=MaterialTheme.typography.labelSmall);Text(fmt(q.volume.toDouble()),fontWeight=FontWeight.Bold)};Sparkline(q.history,Modifier.width(78.dp).height(38.dp),tint)};Spacer(Modifier.height(8.dp));Surface(shape=RoundedCornerShape(9.dp),color=if(q.signal==Signal.STRONG)Green else LightGreen){Text("${q.signal.name}  •  Tap for analysis",color=if(q.signal==Signal.STRONG)Color.White else Green,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(horizontal=9.dp,vertical=5.dp))}}}}
@Composable private fun Stat(label:String,value:Double,modifier:Modifier){Column(modifier){Text(label,color=Muted,style=MaterialTheme.typography.labelSmall);Text("%+.1f%%".format(value),color=if(value>=0)Green else Red,fontWeight=FontWeight.Bold)}}

@Composable private fun DetailScreen(q:Quote,back:()->Unit){var period by rememberSaveable{mutableStateOf("1M")};val score=DemoIntelligenceData.score(q);val fundamentals=DemoIntelligenceData.fundamentals(q.symbol);val events=DemoIntelligenceData.events(q.symbol);val chart=when(period){"1D"->q.history.takeLast(4);"1W"->q.history;"1M"->q.history+listOf(q.price);"3M"->q.history.reversed()+q.history;"1Y"->q.history+q.history.reversed();else->q.history};LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){IconButton(onClick=back){Icon(Icons.Default.ArrowBack,"Back")};StockLogo(q.symbol,40);Spacer(Modifier.width(10.dp));Column{Text(q.companyName,fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.titleLarge);Text(q.symbol,color=Muted)}}};item{Card(shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Column(Modifier.padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("KSh %.2f".format(q.price),style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold);Text("%+.1f%% today".format(q.dailyChange),color=if(q.dailyChange>=0)Green else Red,fontWeight=FontWeight.Bold)};ScoreBadge(score.total,64)};Spacer(Modifier.height(12.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(7.dp)){items(listOf("1D","1W","1M","3M","1Y")){p->FilterChip(selected=period==p,onClick={period=p},label={Text(p)})}};Spacer(Modifier.height(10.dp));Sparkline(chart,Modifier.fillMaxWidth().height(150.dp),if(q.dailyChange>=0)Green else Red)}}};item{ScoreCard(score)};item{Text("Key Fundamentals",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold)};item{FundamentalsCard(fundamentals)};item{Text("Corporate Actions & Events",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold)};item{if(events.isEmpty())EmptyEvents() else EventsCard(events)};item{Card(shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant)){Column(Modifier.padding(13.dp)){Text("About this analysis",fontWeight=FontWeight.Bold);Text("NSE Watcher is an information and analysis tool. Scores and sample metrics are not investment advice, price predictions, or guarantees.",color=Muted,style=MaterialTheme.typography.bodySmall)}}}}

@Composable private fun ScoreBadge(score:Int,size:Int){Surface(Modifier.size(size.dp),shape=CircleShape,color=Green){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text(score.toString(),color=Color.White,fontWeight=FontWeight.ExtraBold,style=if(size>60)MaterialTheme.typography.titleLarge else MaterialTheme.typography.titleMedium);Text("/100",color=Color.White.copy(alpha=.85f),style=MaterialTheme.typography.labelSmall)}}}}
@Composable private fun ScoreCard(score:ScoreBreakdown){Card(shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen)){Column(Modifier.padding(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("NSE Watcher Score",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.ExtraBold);Text(score.label,color=Green,fontWeight=FontWeight.Bold)};ScoreBadge(score.total,52)};Spacer(Modifier.height(9.dp));ScoreLine("Momentum",score.momentum,30);ScoreLine("Volume",score.volume,20);ScoreLine("Trend",score.trend,30);ScoreLine("Liquidity",score.liquidity,20);Spacer(Modifier.height(8.dp));score.reasons.forEach{Text("• $it",color=Muted,style=MaterialTheme.typography.bodySmall)}}}}
@Composable private fun ScoreLine(label:String,value:Int,max:Int){Column(Modifier.padding(vertical=2.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,style=MaterialTheme.typography.labelSmall,color=Muted);Text("$value/$max",style=MaterialTheme.typography.labelSmall,fontWeight=FontWeight.Bold)};LinearProgressIndicator(progress={value.toFloat()/max.toFloat()},modifier=Modifier.fillMaxWidth().height(6.dp),color=Green,trackColor=LightGreen)}}
@Composable private fun FundamentalsCard(f:FundamentalDemo){Column(Modifier.fillMaxWidth()){val rows=listOf("Market cap" to f.marketCap,"P/E" to f.peRatio,"P/B" to f.pbRatio,"EPS" to f.eps,"Dividend yield" to f.dividendYield,"ROE" to f.roe,"Revenue growth" to f.revenueGrowth,"Profit growth" to f.profitGrowth,"Debt / equity" to f.debtToEquity);rows.chunked(2).forEach{pair->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){pair.forEach{(a,b)->Card(Modifier.weight(1f).padding(bottom=8.dp),shape=RoundedCornerShape(13.dp),border=BorderStroke(1.dp,BorderGreen)){Column(Modifier.padding(10.dp)){Text(a,color=Muted,style=MaterialTheme.typography.labelSmall);Text(b,fontWeight=FontWeight.ExtraBold)}}}}}}}
@Composable private fun EventsCard(events:List<CorporateEventDemo>){Column{events.forEach{event->Card(Modifier.fillMaxWidth().padding(bottom=8.dp),shape=RoundedCornerShape(14.dp),border=BorderStroke(1.dp,BorderGreen)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.Top){Surface(Modifier.size(38.dp),shape=RoundedCornerShape(11.dp),color=LightGreen){Icon(Icons.Default.Event,null,tint=Green,modifier=Modifier.padding(9.dp))};Spacer(Modifier.width(10.dp));Column{Text(event.type,fontWeight=FontWeight.Bold,color=Green);Text(event.title,fontWeight=FontWeight.ExtraBold);Text(event.date,color=Muted,style=MaterialTheme.typography.labelSmall);Text(event.detail,color=Muted,style=MaterialTheme.typography.bodySmall)}}}}}}
@Composable private fun EmptyEvents(){Text("No demo corporate actions are loaded for this company yet.",color=Muted,style=MaterialTheme.typography.bodySmall)}

@Composable private fun PortfolioScreen(holdings:List<Holding>,update:(List<Holding>)->Unit){val prices=mapOf("SCOM.KE" to 18.65,"KCB.KE" to 39.85,"EQTY.KE" to 47.20,"ABSA.KE" to 13.40,"COOP.KE" to 15.80,"EABL.KE" to 38.60);val invested=holdings.sumOf{it.shares*it.averagePrice};val current=holdings.sumOf{it.shares*(prices[it.symbol]?:it.averagePrice)};val pnl=current-invested;LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Card(shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Column(Modifier.padding(17.dp)){Text("Portfolio Value",color=Muted);Text("KSh %,.2f".format(current),style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold);Text("%+.2f  (%+.1f%%)".format(pnl,if(invested==0.0)0.0 else pnl/invested*100),color=if(pnl>=0)Green else Red,fontWeight=FontWeight.Bold)}}};item{Text("Holdings",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold)};items(holdings,key={it.symbol}){h->val price=prices[h.symbol]?:h.averagePrice;val value=h.shares*price;val gain=value-h.shares*h.averagePrice;Card(shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(14.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(h.symbol,fontWeight=FontWeight.ExtraBold);Text("${h.shares} shares • Avg KSh %.2f".format(h.averagePrice),color=Muted,style=MaterialTheme.typography.bodySmall)};Column(horizontalAlignment=Alignment.End){Text("KSh %,.2f".format(value),fontWeight=FontWeight.ExtraBold);Text("%+.2f".format(gain),color=if(gain>=0)Green else Red,fontWeight=FontWeight.Bold)}}}};item{Button(onClick={update(holdings+Holding("EQTY.KE",100,45.00))},Modifier.fillMaxWidth()){Icon(Icons.Default.Add,null);Spacer(Modifier.width(5.dp));Text("Add demo holding")}};item{Text("Portfolio values are demo calculations for now.",color=Muted,style=MaterialTheme.typography.bodySmall)}}}

@Composable private fun AlertsScreen(alerts:List<String>,update:(List<String>)->Unit){var showAdd by rememberSaveable{mutableStateOf(false)};LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Smart Alerts",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Text("Demo rules ready for live backend integration.",color=Muted,style=MaterialTheme.typography.bodySmall)};items(alerts){alert->Card(shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=CircleShape,color=LightGreen){Icon(Icons.Default.NotificationsActive,null,tint=Green,modifier=Modifier.padding(8.dp))};Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(alert,fontWeight=FontWeight.SemiBold);Text("Enabled • demo",color=Muted,style=MaterialTheme.typography.labelSmall)};IconButton(onClick={update(alerts-alert)}){Icon(Icons.Default.DeleteOutline,"Delete",tint=Muted)}}}};item{Button(onClick={showAdd=true},Modifier.fillMaxWidth()){Icon(Icons.Default.AddAlert,null);Spacer(Modifier.width(5.dp));Text("Create alert")}};item{Text("Supported live-phase alert types: price, percentage move, volume anomaly, breakout, news, results and corporate actions.",color=Muted,style=MaterialTheme.typography.bodySmall)}};if(showAdd)AlertDialog(onDismissRequest={showAdd=false},title={Text("Create demo alert")},text={Text("The next backend phase will save alert rules such as price above/below, daily gain/loss, unusual volume, breakout, news and corporate actions.")},confirmButton={TextButton(onClick={showAdd=false;update(alerts+"SCOM.KE unusual volume")}){Text("Add")}},dismissButton={TextButton(onClick={showAdd=false}){Text("Cancel")}})}

@Composable private fun NewsScreen(news:List<NewsItem>){LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("NSE News",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Text("Source-backed market news and corporate events will be connected through the backend.",color=Muted,style=MaterialTheme.typography.bodySmall)};items(news,key={it.id}){NewsCard(it)};item{LearnSection()}}}
@Composable private fun LearnSection(){Column{Text("Learn",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Text("Simple market concepts for Kenyan investors",color=Muted,style=MaterialTheme.typography.bodySmall);Spacer(Modifier.height(8.dp));val cards=listOf("P/E ratio" to "Price compared with earnings per share.","Dividend yield" to "Annual dividend relative to share price.","Market cap" to "Share price multiplied by shares outstanding.","Rights issue" to "An offer that lets existing shareholders buy new shares.","Profit warning" to "A company notice that expected results may differ materially.","CDSC" to "Kenya's central securities depository infrastructure.");cards.forEach{(title,body)->Card(Modifier.fillMaxWidth().padding(bottom=7.dp),shape=RoundedCornerShape(13.dp),border=BorderStroke(1.dp,BorderGreen)){Column(Modifier.padding(11.dp)){Text(title,fontWeight=FontWeight.ExtraBold);Text(body,color=Muted,style=MaterialTheme.typography.bodySmall)}}}}}

@Composable private fun SearchDialog(quotes:List<Quote>,open:(Quote)->Unit,close:()->Unit){var query by rememberSaveable{mutableStateOf("")};val results=quotes.filter{it.symbol.contains(query,true)||it.companyName.contains(query,true)};AlertDialog(onDismissRequest=close,title={Text("Search stocks")},text={Column{OutlinedTextField(query,{query=it},singleLine=true,label={Text("Company or symbol")},leadingIcon={Icon(Icons.Default.Search,null)});Spacer(Modifier.height(8.dp));results.forEach{q->Row(Modifier.fillMaxWidth().clickable{open(q)}.padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){StockLogo(q.symbol,32);Spacer(Modifier.width(8.dp));Column{Text(q.symbol,fontWeight=FontWeight.Bold);Text(q.companyName,color=Muted,style=MaterialTheme.typography.bodySmall)}}}}},confirmButton={TextButton(onClick=close){Text("Close")}})}

@Composable private fun DemoBanner(){Card(shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Lightbulb,null,tint=Green,modifier=Modifier.size(27.dp));Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text("Demo Mode",fontWeight=FontWeight.Bold);Text("Sample data only. Live NSE data will be connected through a secure backend, with data freshness clearly shown.",color=Muted,style=MaterialTheme.typography.bodySmall)};Surface(shape=RoundedCornerShape(50),color=Green){Text("DEMO",color=Color.White,fontWeight=FontWeight.Bold,modifier=Modifier.padding(horizontal=11.dp,vertical=6.dp))}}}}
@Composable private fun ErrorState(message:String,retry:()->Unit){Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("Something went wrong",fontWeight=FontWeight.Bold);Text(message,color=Muted);Spacer(Modifier.height(10.dp));Button(onClick=retry){Text("Retry")}}}

@Composable private fun SettingsScreen(username:String,description:String,avatarUri:String?,onBack:()->Unit,onAccount:()->Unit,onAppearance:()->Unit,onNotifications:()->Unit,onSecurity:()->Unit,onHelp:()->Unit){Column(Modifier.fillMaxSize()){SettingsHeader("Settings",onBack);LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{ProfileCard(username,description,avatarUri,onAccount)};item{SettingGroup{SettingRow(Icons.Default.Person,"Account Settings","Manage your profile, email, password",Green,onAccount);SettingRow(Icons.Default.LightMode,"Appearance","Switch between light and dark mode",Color(0xFF6250E8),onAppearance);SettingRow(Icons.Default.Notifications,"Notifications","Alert preferences and push notifications",Color(0xFFFFA000),onNotifications);SettingRow(Icons.Default.Security,"Security","Two-factor authentication and privacy",Color(0xFF1976D2),onSecurity);SettingRow(Icons.Default.HelpOutline,"Help & Support","FAQs, Contact us, about the app",Color(0xFF607D8B),onHelp)}}}}}
@Composable private fun SettingsHeader(title:String,onBack:()->Unit){Surface(color=Green){Row(Modifier.fillMaxWidth().padding(top=9.dp,bottom=13.dp,start=8.dp,end=16.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=onBack){Icon(Icons.Default.ArrowBack,"Back",tint=Color.White)};Text(title,color=Color.White,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)}}}
@Composable private fun ProfileCard(username:String,description:String,avatarUri:String?,onClick:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onClick),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.CenterVertically){Avatar(avatarUri,70);Spacer(Modifier.width(13.dp));Column(Modifier.weight(1f)){Text("Jimmy Mwangi",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.ExtraBold);Text("@$username",color=Green,fontWeight=FontWeight.SemiBold);Text(description,color=Muted,style=MaterialTheme.typography.bodySmall);Text("Kenya investor | NSE Watcher",color=Muted,style=MaterialTheme.typography.bodySmall)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}}
@Composable private fun SettingGroup(content:@Composable ColumnScope.()->Unit){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface),content=content)}
@Composable private fun SettingRow(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,subtitle:String,tint:Color,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(onClick=onClick).padding(12.dp),verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(42.dp),shape=RoundedCornerShape(12.dp),color=tint.copy(alpha=.13f)){Icon(icon,null,tint=tint,modifier=Modifier.padding(10.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(subtitle,color=Muted,style=MaterialTheme.typography.bodySmall)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}

@Composable private fun AccountSettingsScreen(username:String,email:String,password:String,description:String,avatarUri:String?,onBack:()->Unit,onUsername:(String)->Unit,onEmail:(String)->Unit,onPassword:(String)->Unit,onDescription:(String)->Unit,onAvatar:(String?)->Unit){val context=androidx.compose.ui.platform.LocalContext.current;var bitmap by remember{mutableStateOf<ImageBitmap?>(null)};var editing by remember{mutableStateOf<String?>(null)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->if(uri!=null){try{context.contentResolver.takePersistableUriPermission(uri,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};onAvatar(uri.toString())}};LaunchedEffect(avatarUri){bitmap=if(avatarUri==null)null else withContext(Dispatchers.IO){context.contentResolver.openInputStream(Uri.parse(avatarUri))?.use{BitmapFactory.decodeStream(it)?.asImageBitmap()}}};Column(Modifier.fillMaxSize()){SettingsHeader("Account Settings",onBack);LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Card(Modifier.fillMaxWidth().clickable{picker.launch(arrayOf("image/*"))},shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Avatar(bitmap,avatarUri,65);Spacer(Modifier.width(13.dp));Column(Modifier.weight(1f)){Text("Change Profile Picture",fontWeight=FontWeight.Bold);Text("Update your profile photo",color=Muted,style=MaterialTheme.typography.bodySmall)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}};item{AccountRow(Icons.Default.Person,"Username",username){editing="username"}};item{AccountRow(Icons.Default.Email,"Email Address",email){editing="email"}};item{AccountRow(Icons.Default.Lock,"Password","••••••••"){editing="password"}};item{AccountRow(Icons.Default.Description,"Profile Description",description){editing="description"}};item{Button(onClick={onBack()},Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp)){Text("Save Changes",fontWeight=FontWeight.Bold)}}}};editing?.let{field->EditDialog(field,when(field){"username"->username;"email"->email;"password"->password;else->description},{value->when(field){"username"->onUsername(value);"email"->onEmail(value);"password"->onPassword(value);else->onDescription(value)};editing=null},{editing=null})}}
@Composable private fun AccountRow(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,value:String,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(onClick=onClick).padding(horizontal=13.dp,vertical=13.dp),verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(38.dp),shape=RoundedCornerShape(11.dp),color=LightGreen){Icon(icon,null,tint=Green,modifier=Modifier.padding(9.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(value,color=Muted,style=MaterialTheme.typography.bodySmall,maxLines=1)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}
@Composable private fun EditDialog(field:String,initial:String,save:(String)->Unit,cancel:()->Unit){var value by remember(field){mutableStateOf(initial)};AlertDialog(onDismissRequest=cancel,title={Text("Change ${field.replaceFirstChar{it.uppercase()}}")},text={OutlinedTextField(value,{value=it},singleLine=true,label={Text(field.replaceFirstChar{it.uppercase()})},visualTransformation=if(field=="password")PasswordVisualTransformation() else VisualTransformation.None)},confirmButton={TextButton(onClick={save(value)}){Text("Save")}},dismissButton={TextButton(onClick=cancel){Text("Cancel")}})}
@Composable private fun AppearanceScreen(darkMode:Boolean,onBack:()->Unit,onSelect:(Boolean)->Unit){Column(Modifier.fillMaxSize()){SettingsHeader("Appearance",onBack);LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{ThemeOption(Icons.Default.LightMode,"Light Mode","Clean, bright and easy on the eyes",!darkMode,Color(0xFFFFB300)){onSelect(false)}};item{ThemeOption(Icons.Default.DarkMode,"Dark Mode","Easy on the eyes, especially at night",darkMode,Color(0xFF304D78)){onSelect(true)}};item{ThemePreview()};item{Button(onClick=onBack,Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp)){Text("Apply",fontWeight=FontWeight.Bold)}}}}}
@Composable private fun ThemeOption(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,subtitle:String,selected:Boolean,tint:Color,onClick:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onClick),shape=RoundedCornerShape(16.dp),border=BorderStroke(if(selected)2.dp else 1.dp,if(selected)Green else BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(43.dp),shape=CircleShape,color=tint.copy(alpha=.13f)){Icon(icon,null,tint=tint,modifier=Modifier.padding(10.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(subtitle,color=Muted,style=MaterialTheme.typography.bodySmall)};if(selected)Icon(Icons.Default.CheckCircle,null,tint=Green)else Icon(Icons.Default.RadioButtonUnchecked,null,tint=Muted)}}}
@Composable private fun ThemePreview(){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=Color(0xFFF7FAF8))){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.spacedBy(12.dp)){MiniPhonePreview(false,Modifier.weight(1f));MiniPhonePreview(true,Modifier.weight(1f))}}}
@Composable private fun MiniPhonePreview(dark:Boolean,modifier:Modifier){val bg=if(dark)Color(0xFF102018)else Color.White;val fg=if(dark)Color.White else TextDark;Surface(modifier.height(170.dp),shape=RoundedCornerShape(18.dp),color=bg,border=BorderStroke(1.dp,if(dark)Color(0xFF355044)else Color(0xFFDDE8E1))){Column(Modifier.padding(10.dp)){Text("NSE Watcher",color=fg,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(7.dp));Surface(Modifier.fillMaxWidth().height(48.dp),shape=RoundedCornerShape(10.dp),color=if(dark)Color(0xFF203129)else LightGreen){Column(Modifier.padding(7.dp)){Text("●  Demo Market",color=Green,style=MaterialTheme.typography.labelSmall,fontWeight=FontWeight.Bold);Sparkline(listOf(2.0,3.0,2.5,4.0,3.5,5.0),Modifier.fillMaxWidth().height(20.dp),Green)}};Spacer(Modifier.height(7.dp));Text("SCOM      +1.40%",color=fg,style=MaterialTheme.typography.labelSmall);Text("KCB         +0.30%",color=fg,style=MaterialTheme.typography.labelSmall);Text("ABSA        -1.10%",color=Red,style=MaterialTheme.typography.labelSmall)}}}
@Composable private fun Avatar(uri:String?,size:Int){val context=androidx.compose.ui.platform.LocalContext.current;var bitmap by remember(uri){mutableStateOf<ImageBitmap?>(null)};LaunchedEffect(uri){bitmap=if(uri==null)null else withContext(Dispatchers.IO){context.contentResolver.openInputStream(Uri.parse(uri))?.use{BitmapFactory.decodeStream(it)?.asImageBitmap()}}};Avatar(bitmap,uri,size)}
@Composable private fun Avatar(bitmap:ImageBitmap?,uri:String?,size:Int){if(bitmap!=null)Image(bitmap,"Profile photo",Modifier.size(size.dp).clip(CircleShape))else Surface(Modifier.size(size.dp),shape=CircleShape,color=LightGreen){Icon(Icons.Default.Person,"Profile",tint=Green,modifier=Modifier.padding((size/4).dp))}}
private fun fmt(value:Double):String=when{value>=1_000_000_000->"%.1fB".format(value/1_000_000_000);value>=1_000_000->"%.1fM".format(value/1_000_000);value>=1_000->"%.1fK".format(value/1_000);else->"%.0f".format(value)}
