@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
package ke.co.nsewatcher

import android.app.Application
import android.content.Context
import android.content.SharedPreferences
import android.graphics.BitmapFactory
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import ke.co.nsewatcher.data.DemoMarketRepository
import ke.co.nsewatcher.data.MarketRepository
import ke.co.nsewatcher.domain.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

private val Green = Color(0xFF00A859)
private val LightGreen = Color(0xFFE8F8EF)
private val Red = Color(0xFFE53935)
private val TextDark = Color(0xFF102018)
private val Muted = Color(0xFF68766F)
private val BorderGreen = Color(0xFFE0EAE4)
private val AppColors = lightColorScheme(primary=Green,onPrimary=Color.White,secondary=Green,tertiary=Green,background=Color.White,surface=Color.White,surfaceVariant=Color(0xFFF4F7F5),onBackground=TextDark,onSurface=TextDark,onSurfaceVariant=Muted,error=Red)
private val DarkAppColors = darkColorScheme(primary=Color(0xFF35C979),onPrimary=Color(0xFF00391C),secondary=Color(0xFF35C979),background=Color(0xFF0E1511),surface=Color(0xFF16201A),surfaceVariant=Color(0xFF223027),onBackground=Color.White,onSurface=Color.White,onSurfaceVariant=Color(0xFFB8C6BD),error=Color(0xFFFF6B64))

data class AppState(val snapshot: MarketSnapshot?=null,val news: List<NewsItem> = emptyList(),val loading:Boolean=true,val error:String?=null)
data class Holding(val symbol:String,val shares:Int,val averagePrice:Double)

class MainActivity:ComponentActivity(){
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{NSEWatcherApp(MarketViewModel(application),getSharedPreferences("nse_watcher_user",Context.MODE_PRIVATE))}}
}

class MarketViewModel(application:Application,private val repository:MarketRepository=DemoMarketRepository(application)):ViewModel(){
    private val _state=MutableStateFlow(AppState());val state:StateFlow<AppState> = _state
    init{refresh()}
    fun refresh()=viewModelScope.launch{
        _state.value=_state.value.copy(loading=true,error=null)
        repository.snapshot(true).onSuccess{s->repository.news().onSuccess{n->_state.value=AppState(s,n,false)}}.onFailure{_state.value=_state.value.copy(loading=false,error=it.message?:"Unable to load market data")}
    }
    fun add(symbol:String)=viewModelScope.launch{repository.addSymbol(symbol);refresh()}
    fun remove(symbol:String)=viewModelScope.launch{repository.removeSymbol(symbol);refresh()}
}

@Composable fun NSEWatcherApp(vm:MarketViewModel,prefs:SharedPreferences){
    val state by vm.state.collectAsStateWithLifecycle()
    var tab by rememberSaveable{mutableIntStateOf(0)}
    var selected by remember{mutableStateOf<Quote?>(null)}
    var settings by rememberSaveable{mutableStateOf(false)}
    var account by rememberSaveable{mutableStateOf(false)}
    var appearance by rememberSaveable{mutableStateOf(false)}
    var infoDialog by rememberSaveable{mutableStateOf<String?>(null)}
    var darkMode by rememberSaveable{mutableStateOf(prefs.getBoolean("dark_mode",false))}
    var username by rememberSaveable{mutableStateOf(prefs.getString("username","jimmymwangi")?:"jimmymwangi")}
    var email by rememberSaveable{mutableStateOf(prefs.getString("email","jimmy.mwangi@email.com")?:"jimmy.mwangi@email.com")}
    var password by rememberSaveable{mutableStateOf(prefs.getString("password","password123")?:"password123")}
    var description by rememberSaveable{mutableStateOf(prefs.getString("description","Building wealth, one stock at a time.")?:"Building wealth, one stock at a time.")}
    var avatarUri by rememberSaveable{mutableStateOf(prefs.getString("avatar_uri",null))}
    var holdings by remember{mutableStateOf(listOf(Holding("SCOM.KE",500,21.50),Holding("KCB.KE",200,38.00)))}
    var alerts by remember{mutableStateOf(listOf("SCOM.KE above KSh 30.00","KCB.KE daily gain above 5%"))}
    fun savePrefs(){prefs.edit().putBoolean("dark_mode",darkMode).putString("username",username).putString("email",email).putString("password",password).putString("description",description).putString("avatar_uri",avatarUri).apply()}
    val internalBackEnabled=settings||account||appearance||selected!=null||tab!=0
    BackHandler(enabled=internalBackEnabled){when{account->{account=false};appearance->{appearance=false};settings->{settings=false};selected!=null->{selected=null};tab!=0->{tab=0}}}
    MaterialTheme(colorScheme=if(darkMode)DarkAppColors else AppColors){
        Surface(Modifier.fillMaxSize(),color=MaterialTheme.colorScheme.background){
            when{
                account->AccountSettingsScreen(username,email,password,description,avatarUri,{account=false},{username=it},{email=it},{password=it},{description=it},{avatarUri=it;savePrefs()})
                appearance->AppearanceScreen(darkMode,{appearance=false}){darkMode=it;savePrefs()}
                settings->SettingsScreen(username,description,avatarUri,{settings=false},{account=true},{appearance=true},{tab=3;settings=false},{infoDialog="Security settings will be available when account security is connected."},{infoDialog="Help and support will be connected before the live release."})
                selected!=null->DetailScreen(selected!!){selected=null}
                else->MainShell(state,vm,tab,{tab=it},{selected=it},{settings=true},holdings,{holdings=it},alerts,{alerts=it},{tab=1})
            }
            infoDialog?.let{msg->AlertDialog(onDismissRequest={infoDialog=null},confirmButton={TextButton(onClick={infoDialog=null}){Text("OK")}},title={Text("NSE Watcher")},text={Text(msg)})}
        }
    }
}

@Composable private fun MainShell(state:AppState,vm:MarketViewModel,tab:Int,setTab:(Int)->Unit,open:(Quote)->Unit,openSettings:()->Unit,holdings:List<Holding>,setHoldings:(List<Holding>)->Unit,alerts:List<String>,setAlerts:(List<String>)->Unit,viewAllWatchlist:()->Unit){
    Scaffold(topBar={TopBar(openSettings)},bottomBar={NavigationBar(containerColor=MaterialTheme.colorScheme.surface){val nav=listOf("Home" to Icons.Default.Home,"Watchlist" to Icons.Default.Star,"Portfolio" to Icons.Default.AccountBalanceWallet,"Alerts" to Icons.Default.Notifications,"News" to Icons.Default.Article);nav.forEachIndexed{i,item->NavigationBarItem(selected=tab==i,onClick={setTab(i)},icon={Icon(item.second,item.first)},label={Text(item.first)},colors=NavigationBarItemDefaults.colors(selectedIconColor=Green,selectedTextColor=Green,indicatorColor=LightGreen,unselectedIconColor=Muted,unselectedTextColor=Muted))}}}){padding->Box(Modifier.fillMaxSize().padding(padding)){when{state.loading->CircularProgressIndicator(Modifier.align(Alignment.Center),color=Green);state.error!=null&&state.snapshot==null->ErrorState(state.error!!,vm::refresh);tab==0->Dashboard(state,open,viewAllWatchlist);tab==1->Watchlist(state.snapshot?.quotes.orEmpty(),vm::add,vm::remove,open);tab==2->PortfolioScreen(holdings,setHoldings);tab==3->AlertsScreen(alerts,setAlerts);else->NewsScreen(state.news)}}}}

@Composable private fun TopBar(openSettings:()->Unit){TopAppBar(colors=TopAppBarDefaults.topAppBarColors(containerColor=MaterialTheme.colorScheme.surface),title={Row(verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(38.dp),shape=RoundedCornerShape(11.dp),color=LightGreen){Icon(Icons.Default.BarChart,null,tint=Green,modifier=Modifier.padding(7.dp))};Spacer(Modifier.width(9.dp));Column{Text("NSE Watcher",fontWeight=FontWeight.ExtraBold);Text("Track • Analyze • Grow",style=MaterialTheme.typography.labelSmall,color=Muted)}}},actions={IconButton(onClick={}){Icon(Icons.Default.Search,"Search",tint=Green)};IconButton(onClick=openSettings){Icon(Icons.Default.Settings,"Settings",tint=Green)}})}

@Composable private fun Dashboard(state:AppState,open:(Quote)->Unit,viewAll:()->Unit){
    val quotes=state.snapshot?.quotes.orEmpty();val gainers=quotes.sortedByDescending{it.dailyChange};val losers=quotes.sortedBy{it.dailyChange}
    LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){
        item{MarketHero()};item{MarketSummary(quotes)}
        item{SectionTitle("🔥 Market Movers","Top gainers and losers")}
        item{MarketMovers(gainers.firstOrNull(),losers.firstOrNull(),open)}
        item{SectionTitleWithAction("⭐ Your Watchlist","Top 6 tracked","View all",viewAll)}
        item{LazyRow(contentPadding=PaddingValues(horizontal=1.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){items(quotes.take(6),key={it.symbol}){q->HorizontalStockCard(q){open(q)}}}}
        item{InsightCard(quotes)}
        item{SectionTitle("📰 Latest News","From your tracked stocks")}
        items(state.news.take(3),key={it.id}){NewsCard(it)}
        item{DemoBanner()}
    }
}

@Composable private fun MarketMovers(gainer:Quote?,loser:Quote?,open:(Quote)->Unit){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(vertical=13.dp)){MoverColumn("TOP GAINER",gainer,true,Modifier.weight(1f),open);Box(Modifier.width(1.dp).height(76.dp).background(BorderGreen));MoverColumn("TOP LOSER",loser,false,Modifier.weight(1f),open)}}}
@Composable private fun MoverColumn(label:String,q:Quote?,positive:Boolean,modifier:Modifier,open:(Quote)->Unit){Column(modifier.clickable{q?.let(open)}.padding(horizontal=15.dp),horizontalAlignment=if(positive)Alignment.Start else Alignment.End){Text(label,style=MaterialTheme.typography.labelSmall,fontWeight=FontWeight.Bold,color=if(positive)Green else Red);Text(q?.symbol?:"—",fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.titleMedium);Text(q?.companyName?:"No data",style=MaterialTheme.typography.bodySmall,color=Muted,maxLines=1);Text(q?.let{"%+.1f%%".format(it.dailyChange)}?:"—",fontWeight=FontWeight.ExtraBold,color=if(positive)Green else Red)}}

@Composable private fun MarketHero(){Card(shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Row(Modifier.fillMaxWidth().padding(15.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(9.dp).clip(CircleShape).background(Green));Spacer(Modifier.width(6.dp));Text("Market Status",fontWeight=FontWeight.SemiBold)};Text("DEMO MARKET",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold,color=Green);Text("Sample data • not live prices",style=MaterialTheme.typography.bodySmall,color=Muted)};Column(horizontalAlignment=Alignment.End){Text("NSE",fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.titleLarge);Text("Nairobi Securities Exchange",style=MaterialTheme.typography.labelSmall,color=Muted)}}}}
@Composable private fun MarketSummary(quotes:List<Quote>){val gain=quotes.count{it.dailyChange>0};val loss=quotes.count{it.dailyChange<0};val flat=quotes.size-gain-loss;Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(4.dp)){SummaryStat("Stocks",quotes.size.toString(),Modifier.weight(1f));SummaryStat("Gainers",gain.toString(),Modifier.weight(1f),Green);SummaryStat("Losers",loss.toString(),Modifier.weight(1f),Red);SummaryStat("Flat",flat.toString(),Modifier.weight(1f))}}
@Composable private fun SummaryStat(label:String,value:String,modifier:Modifier,tint:Color=TextDark){Card(modifier,shape=RoundedCornerShape(13.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(9.dp)){Text(value,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.ExtraBold,color=tint);Text(label,style=MaterialTheme.typography.labelSmall,color=Muted)}}}
@Composable private fun SectionTitle(title:String,subtitle:String){Column{Text(title,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Text(subtitle,style=MaterialTheme.typography.bodySmall,color=Muted)}}
@Composable private fun SectionTitleWithAction(title:String,subtitle:String,action:String,onAction:()->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Bottom){Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Text(subtitle,style=MaterialTheme.typography.bodySmall,color=Muted)};TextButton(onClick=onAction){Text(action,color=Green,fontWeight=FontWeight.Bold)}}}

@Composable private fun HorizontalStockCard(q:Quote,open:()->Unit){val tint=if(q.dailyChange>=0)Green else Red;Card(Modifier.width(210.dp).clickable(onClick=open),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(13.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(q.symbol,fontWeight=FontWeight.ExtraBold);Text(q.companyName,color=Muted,style=MaterialTheme.typography.labelSmall,maxLines=1)};Text("%+.1f%%".format(q.dailyChange),color=tint,fontWeight=FontWeight.Bold)};Spacer(Modifier.height(7.dp));Text("KSh %.2f".format(q.price),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Sparkline(q.history,Modifier.fillMaxWidth().height(40.dp),tint);Spacer(Modifier.height(6.dp));Text("%s  •  KSh %.2f".format(q.signal.name,q.price),style=MaterialTheme.typography.labelSmall,color=tint,fontWeight=FontWeight.Bold)}}}

@Composable private fun StockCard(q:Quote,open:()->Unit){val tint=if(q.dailyChange>=0)Green else Red;Card(Modifier.fillMaxWidth().clickable(onClick=open),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(14.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(q.companyName,fontWeight=FontWeight.ExtraBold);Text(q.symbol,color=Muted,style=MaterialTheme.typography.bodySmall)};Column(horizontalAlignment=Alignment.End){Text("KSh %.2f".format(q.price),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.ExtraBold);Text("%+.1f%%".format(q.dailyChange),color=tint,fontWeight=FontWeight.Bold)}};Spacer(Modifier.height(8.dp));Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Stat("1W",q.weeklyChange,Modifier.weight(1f));Stat("1M",q.monthlyChange,Modifier.weight(1f));Column(Modifier.weight(1.2f)){Text("Volume",color=Muted,style=MaterialTheme.typography.labelSmall);Text(fmt(q.volume.toDouble()),fontWeight=FontWeight.Bold)};Sparkline(q.history,Modifier.width(78.dp).height(38.dp),tint)};Spacer(Modifier.height(8.dp));Surface(shape=RoundedCornerShape(9.dp),color=if(q.signal==Signal.STRONG)Green else LightGreen){Text("${q.signal.name}  •  Tap for details",color=if(q.signal==Signal.STRONG)Color.White else Green,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(horizontal=9.dp,vertical=5.dp))}}}}
@Composable private fun Stat(label:String,value:Double,modifier:Modifier){Column(modifier){Text(label,color=Muted,style=MaterialTheme.typography.labelSmall);Text("%+.1f%%".format(value),color=if(value>=0)Green else Red,fontWeight=FontWeight.Bold)}}
@Composable private fun Sparkline(values:List<Double>,modifier:Modifier,tint:Color){Canvas(modifier){if(values.size>1){val min=values.minOrNull()?:0.0;val max=values.maxOrNull()?:1.0;val range=(max-min).takeIf{it>0}?:1.0;val path=Path();values.forEachIndexed{i,v->val x=size.width*i/values.lastIndex;val y=size.height-((v-min)/range).toFloat()*size.height;if(i==0)path.moveTo(x,y)else path.lineTo(x,y)};drawPath(path,tint,style=androidx.compose.ui.graphics.drawscope.Stroke(width=4f))}}}
@Composable private fun InsightCard(quotes:List<Quote>){val best=quotes.maxByOrNull{it.dailyChange};val worst=quotes.minByOrNull{it.dailyChange};Card(shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant)){Row(Modifier.fillMaxWidth().padding(14.dp)){Icon(Icons.Default.Lightbulb,null,tint=Green);Spacer(Modifier.width(9.dp));Column{Text("Demo insight",fontWeight=FontWeight.Bold);Text("${best?.symbol?:"—"} has the strongest daily move while ${worst?.symbol?:"—"} is the weakest in this sample.",color=Muted,style=MaterialTheme.typography.bodySmall)}}}}

@Composable private fun Watchlist(quotes:List<Quote>,add:(String)->Unit,remove:(String)->Unit,open:(Quote)->Unit){var search by rememberSaveable{mutableStateOf("")};var expanded by remember{mutableStateOf(false)};val catalog=listOf("SCOM.KE","EQTY.KE","KCB.KE","ABSA.KE","COOP.KE","EABL.KE","KPLC.KE");val filtered=quotes.filter{it.companyName.contains(search,true)||it.symbol.contains(search,true)};Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth().padding(16.dp),verticalAlignment=Alignment.CenterVertically){OutlinedTextField(search,{search=it},Modifier.weight(1f),singleLine=true,label={Text("Search stocks")},leadingIcon={Icon(Icons.Default.Search,null)});Spacer(Modifier.width(8.dp));Box{Button(onClick={expanded=true}){Icon(Icons.Default.Add,null);Text("Add")};DropdownMenu(expanded,{expanded=false}){catalog.forEach{sym->DropdownMenuItem(text={Text(sym)},onClick={add(sym);expanded=false})}}}};LazyColumn(contentPadding=PaddingValues(horizontal=16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(filtered,key={it.symbol}){q->StockCard(q){open(q)};TextButton(onClick={remove(q.symbol)}){Icon(Icons.Default.DeleteOutline,null);Text("Remove from watchlist")}}}}}

@Composable private fun PortfolioScreen(holdings:List<Holding>,update:(List<Holding>)->Unit){val prices=mapOf("SCOM.KE" to 27.45,"KCB.KE" to 42.10,"EQTY.KE" to 58.20,"ABSA.KE" to 18.90,"COOP.KE" to 15.80,"EABL.KE" to 38.60);val invested=holdings.sumOf{it.shares*it.averagePrice};val current=holdings.sumOf{it.shares*(prices[it.symbol]?:it.averagePrice)};val pnl=current-invested;LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Card(shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Column(Modifier.padding(17.dp)){Text("Portfolio Value",color=Muted);Text("KSh %,.2f".format(current),style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold);Text("%+.2f  (%+.1f%%)".format(pnl,if(invested==0.0)0.0 else pnl/invested*100),color=if(pnl>=0)Green else Red,fontWeight=FontWeight.Bold)}}};item{SectionTitle("Holdings","Track your demo investments")};items(holdings,key={it.symbol}){h->val price=prices[h.symbol]?:h.averagePrice;val value=h.shares*price;val gain=value-h.shares*h.averagePrice;Card(shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(14.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(h.symbol,fontWeight=FontWeight.ExtraBold);Text("${h.shares} shares • Avg KSh %.2f".format(h.averagePrice),color=Muted,style=MaterialTheme.typography.bodySmall)};Column(horizontalAlignment=Alignment.End){Text("KSh %,.2f".format(value),fontWeight=FontWeight.ExtraBold);Text("%+.2f".format(gain),color=if(gain>=0)Green else Red,fontWeight=FontWeight.Bold)}}}};item{Button(onClick={update(holdings+Holding("EQTY.KE",100,50.00))},Modifier.fillMaxWidth()){Icon(Icons.Default.Add,null);Spacer(Modifier.width(5.dp));Text("Add demo holding")}};item{Text("Portfolio values are demo calculations for now.",color=Muted,style=MaterialTheme.typography.bodySmall)}}}

@Composable private fun AlertsScreen(alerts:List<String>,update:(List<String>)->Unit){LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{SectionTitle("🔔 Price Alerts","Never miss a move")};items(alerts){alert->Card(shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=CircleShape,color=LightGreen){Icon(Icons.Default.NotificationsActive,null,tint=Green,modifier=Modifier.padding(8.dp))};Spacer(Modifier.width(10.dp));Text(alert,Modifier.weight(1f),fontWeight=FontWeight.SemiBold);IconButton(onClick={update(alerts-alert)}){Icon(Icons.Default.DeleteOutline,"Delete",tint=Muted)}}}};item{Button(onClick={update(alerts+"SCOM.KE above KSh 30.00")},Modifier.fillMaxWidth()){Icon(Icons.Default.AddAlert,null);Spacer(Modifier.width(5.dp));Text("Create demo alert")}}}}
@Composable private fun NewsScreen(news:List<NewsItem>){LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{SectionTitle("📰 NSE News","News linked to your watchlist")};items(news,key={it.id}){NewsCard(it)};item{Text("Live news and corporate actions will be connected later.",color=Muted,style=MaterialTheme.typography.bodySmall)}}}
@Composable private fun NewsCard(item:NewsItem){Card(shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.CenterVertically){NewsThumbnail(item.category);Spacer(Modifier.width(11.dp));Column(Modifier.weight(1f)){Text(item.category,color=Green,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelSmall);Text(item.headline,fontWeight=FontWeight.Bold,maxLines=3);Spacer(Modifier.height(4.dp));Text("${item.source} • ${item.publishedAt}",color=Muted,style=MaterialTheme.typography.bodySmall)}}}}
@Composable private fun NewsThumbnail(category:String){val icon=when(category){"Company"->Icons.Default.Business;"Market"->Icons.Default.TrendingUp;else->Icons.Default.Article};Surface(Modifier.size(92.dp),shape=RoundedCornerShape(14.dp),color=LightGreen){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Icon(icon,null,tint=Green,modifier=Modifier.size(40.dp))}}}

@Composable private fun DetailScreen(q:Quote,back:()->Unit){LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){IconButton(onClick=back){Icon(Icons.Default.ArrowBack,"Back")};Column{Text(q.companyName,fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.titleLarge);Text(q.symbol,color=Muted)}}};item{Card(shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Column(Modifier.padding(17.dp)){Text("KSh %.2f".format(q.price),style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold);Text("%+.1f%% today".format(q.dailyChange),color=if(q.dailyChange>=0)Green else Red,fontWeight=FontWeight.Bold);Spacer(Modifier.height(12.dp));Sparkline(q.history,Modifier.fillMaxWidth().height(150.dp),if(q.dailyChange>=0)Green else Red)}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){DetailStat("Day high","%.2f".format(q.dayHigh),Modifier.weight(1f));DetailStat("Day low","%.2f".format(q.dayLow),Modifier.weight(1f));DetailStat("Volume",fmt(q.volume.toDouble()),Modifier.weight(1f))}};item{Card(shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Column(Modifier.padding(15.dp)){Text("Signal: ${q.signal.name}",color=Green,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.height(5.dp));Text(q.signalExplanation,color=Muted)}}}}}
@Composable private fun DetailStat(label:String,value:String,modifier:Modifier){Column(modifier){Text(label,color=Muted,style=MaterialTheme.typography.labelSmall);Text(value,fontWeight=FontWeight.Bold)}}
@Composable private fun DemoBanner(){Card(shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=LightGreen)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Lightbulb,null,tint=Green);Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text("Demo Mode",fontWeight=FontWeight.Bold);Text("This is sample data. Real NSE data will be available once we connect the live backend.",color=Muted,style=MaterialTheme.typography.bodySmall)};Surface(shape=RoundedCornerShape(50),color=Green){Text("DEMO",color=Color.White,fontWeight=FontWeight.Bold,modifier=Modifier.padding(horizontal=11.dp,vertical=6.dp))}}}}
@Composable private fun ErrorState(message:String,retry:()->Unit){Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("Something went wrong",fontWeight=FontWeight.Bold);Text(message,color=Muted);Spacer(Modifier.height(10.dp));Button(onClick=retry){Text("Retry")}}}

@Composable private fun SettingsScreen(username:String,description:String,avatarUri:String?,onBack:()->Unit,onAccount:()->Unit,onAppearance:()->Unit,onNotifications:()->Unit,onSecurity:()->Unit,onHelp:()->Unit){Column(Modifier.fillMaxSize()){SettingsHeader("Settings",onBack);LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{ProfileCard(username,description,avatarUri,onAccount)};item{SettingGroup{SettingRow(Icons.Default.Person,"Account Settings","Manage your profile, email, password",Green,onAccount);SettingRow(Icons.Default.LightMode,"Appearance","Switch between light and dark mode",Color(0xFF6250E8),onAppearance);SettingRow(Icons.Default.Notifications,"Notifications","Alert preferences and push notifications",Color(0xFFFFA000),onNotifications);SettingRow(Icons.Default.Security,"Security","Two-factor authentication and privacy",Color(0xFF1976D2),onSecurity);SettingRow(Icons.Default.HelpOutline,"Help & Support","FAQs, Contact us, about the app",Color(0xFF607D8B),onHelp)}}}}}
@Composable private fun SettingsHeader(title:String,onBack:()->Unit){Surface(color=Green){Row(Modifier.fillMaxWidth().padding(top=9.dp,bottom=13.dp,start=8.dp,end=16.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onClick=onBack){Icon(Icons.Default.ArrowBack,"Back",tint=Color.White)};Text(title,color=Color.White,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)}}}
@Composable private fun ProfileCard(username:String,description:String,avatarUri:String?,onClick:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onClick),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.CenterVertically){Avatar(avatarUri,70);Spacer(Modifier.width(13.dp));Column(Modifier.weight(1f)){Text("Jimmy Mwangi",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.ExtraBold);Text("@$username",color=Green,fontWeight=FontWeight.SemiBold);Text(description,color=Muted,style=MaterialTheme.typography.bodySmall);Text("Kenya investor | NSE Watcher",color=Muted,style=MaterialTheme.typography.bodySmall)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}}
@Composable private fun SettingGroup(content:@Composable ColumnScope.()->Unit){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface),content=content)}
@Composable private fun SettingRow(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,subtitle:String,tint:Color,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(onClick=onClick).padding(12.dp),verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(42.dp),shape=RoundedCornerShape(12.dp),color=tint.copy(alpha=.13f)){Icon(icon,null,tint=tint,modifier=Modifier.padding(10.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(subtitle,color=Muted,style=MaterialTheme.typography.bodySmall)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}

@Composable private fun AccountSettingsScreen(username:String,email:String,password:String,description:String,avatarUri:String?,onBack:()->Unit,onUsername:(String)->Unit,onEmail:(String)->Unit,onPassword:(String)->Unit,onDescription:(String)->Unit,onAvatar:(String?)->Unit){val context=androidx.compose.ui.platform.LocalContext.current;var bitmap by remember{mutableStateOf<ImageBitmap?>(null)};var editing by remember{mutableStateOf<String?>(null)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->if(uri!=null){try{context.contentResolver.takePersistableUriPermission(uri,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};onAvatar(uri.toString())}};LaunchedEffect(avatarUri){bitmap=if(avatarUri==null)null else withContext(Dispatchers.IO){context.contentResolver.openInputStream(Uri.parse(avatarUri))?.use{BitmapFactory.decodeStream(it)?.asImageBitmap()}}};Column(Modifier.fillMaxSize()){SettingsHeader("Account Settings",onBack);LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Card(Modifier.fillMaxWidth().clickable{picker.launch(arrayOf("image/*"))},shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Avatar(bitmap,avatarUri,65);Spacer(Modifier.width(13.dp));Column(Modifier.weight(1f)){Text("Change Profile Picture",fontWeight=FontWeight.Bold);Text("Update your profile photo",color=Muted,style=MaterialTheme.typography.bodySmall)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}};item{AccountRow(Icons.Default.Person,"Username",username){editing="username"}};item{AccountRow(Icons.Default.Email,"Email Address",email){editing="email"}};item{AccountRow(Icons.Default.Lock,"Password","••••••••"){editing="password"}};item{AccountRow(Icons.Default.Description,"Profile Description",description){editing="description"}};item{Button(onClick={onBack()},Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp)){Text("Save Changes",fontWeight=FontWeight.Bold)}}}};editing?.let{field->EditDialog(field,when(field){"username"->username;"email"->email;"password"->password;else->description},{value->when(field){"username"->onUsername(value);"email"->onEmail(value);"password"->onPassword(value);else->onDescription(value)};editing=null},{editing=null})}}
@Composable private fun AccountRow(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,value:String,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(onClick=onClick).padding(horizontal=13.dp,vertical=13.dp),verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(38.dp),shape=RoundedCornerShape(11.dp),color=LightGreen){Icon(icon,null,tint=Green,modifier=Modifier.padding(9.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(value,color=Muted,style=MaterialTheme.typography.bodySmall,maxLines=1)};Icon(Icons.Default.ChevronRight,null,tint=Muted)}}
@Composable private fun EditDialog(field:String,initial:String,save:(String)->Unit,cancel:()->Unit){var value by remember(field){mutableStateOf(initial)};AlertDialog(onDismissRequest=cancel,title={Text("Change ${field.replaceFirstChar{it.uppercase()}}")},text={OutlinedTextField(value,{value=it},singleLine=true,label={Text(field.replaceFirstChar{it.uppercase()})},visualTransformation=if(field=="password")PasswordVisualTransformation() else VisualTransformation.None)},confirmButton={TextButton(onClick={save(value)}){Text("Save")}},dismissButton={TextButton(onClick=cancel){Text("Cancel")}})}

@Composable private fun AppearanceScreen(darkMode:Boolean,onBack:()->Unit,onSelect:(Boolean)->Unit){Column(Modifier.fillMaxSize()){SettingsHeader("Appearance",onBack);LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{ThemeOption(Icons.Default.LightMode,"Light Mode","Clean, bright and easy on the eyes",!darkMode,Color(0xFFFFB300)){onSelect(false)}};item{ThemeOption(Icons.Default.DarkMode,"Dark Mode","Easy on the eyes, especially at night",darkMode,Color(0xFF304D78)){onSelect(true)}};item{ThemePreview()};item{Button(onClick=onBack,Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp)){Text("Apply",fontWeight=FontWeight.Bold)}}}}}
@Composable private fun ThemeOption(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,subtitle:String,selected:Boolean,tint:Color,onClick:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onClick),shape=RoundedCornerShape(16.dp),border=BorderStroke(if(selected)2.dp else 1.dp,if(selected)Green else BorderGreen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(43.dp),shape=CircleShape,color=tint.copy(alpha=.13f)){Icon(icon,null,tint=tint,modifier=Modifier.padding(10.dp))};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(subtitle,color=Muted,style=MaterialTheme.typography.bodySmall)};if(selected)Icon(Icons.Default.CheckCircle,null,tint=Green)else Icon(Icons.Default.RadioButtonUnchecked,null,tint=Muted)}}}
@Composable private fun ThemePreview(){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),border=BorderStroke(1.dp,BorderGreen),colors=CardDefaults.cardColors(containerColor=Color(0xFFF7FAF8))){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.spacedBy(12.dp)){MiniPhonePreview(false,Modifier.weight(1f));MiniPhonePreview(true,Modifier.weight(1f))}}}
@Composable private fun MiniPhonePreview(dark:Boolean,modifier:Modifier){val bg=if(dark)Color(0xFF102018)else Color.White;val fg=if(dark)Color.White else TextDark;Surface(modifier.height(170.dp),shape=RoundedCornerShape(18.dp),color=bg,border=BorderStroke(1.dp,if(dark)Color(0xFF355044)else Color(0xFFDDE8E1))){Column(Modifier.padding(10.dp)){Text("NSE Watcher",color=fg,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(7.dp));Surface(Modifier.fillMaxWidth().height(48.dp),shape=RoundedCornerShape(10.dp),color=if(dark)Color(0xFF203129)else LightGreen){Column(Modifier.padding(7.dp)){Text("●  Market Open",color=Green,style=MaterialTheme.typography.labelSmall,fontWeight=FontWeight.Bold);Sparkline(listOf(2.0,3.0,2.5,4.0,3.5,5.0),Modifier.fillMaxWidth().height(20.dp),Green)}};Spacer(Modifier.height(7.dp));Text("SCOM      +2.15%",color=fg,style=MaterialTheme.typography.labelSmall);Text("KCB         +1.12%",color=fg,style=MaterialTheme.typography.labelSmall);Text("EQTY        -0.65%",color=Red,style=MaterialTheme.typography.labelSmall)}}}

@Composable private fun Avatar(uri:String?,size:Int){val context=androidx.compose.ui.platform.LocalContext.current;var bitmap by remember(uri){mutableStateOf<ImageBitmap?>(null)};LaunchedEffect(uri){bitmap=if(uri==null)null else withContext(Dispatchers.IO){context.contentResolver.openInputStream(Uri.parse(uri))?.use{BitmapFactory.decodeStream(it)?.asImageBitmap()}}};Avatar(bitmap,uri,size)}
@Composable private fun Avatar(bitmap:ImageBitmap?,uri:String?,size:Int){if(bitmap!=null)Image(bitmap,"Profile photo",Modifier.size(size.dp).clip(CircleShape))else Surface(Modifier.size(size.dp),shape=CircleShape,color=LightGreen){Icon(Icons.Default.Person,"Profile",tint=Green,modifier=Modifier.padding((size/4).dp))}}
private fun fmt(value:Double):String=when{value>=1_000_000_000->"%.1fB".format(value/1_000_000_000);value>=1_000_000->"%.1fM".format(value/1_000_000);value>=1_000->"%.1fK".format(value/1_000);else->"%.0f".format(value)}
